# Site
name: "ZIKAPANAM"
title: "ZIKAPANAM"
description: "Le Blog de ZIKAPANAM, une association loi 1901 dont le but est d'organiser des rencontres musicales (Jams & répétitions) ouvert à tous sur Paris et petites couronnes ! (selon votre niveau, nous avons des solutions)."
logo: assets/images/logo.png
favicon: assets/images/favicon.ico'
baseurl: 
# google_analytics: 'UA-46278016-1'
# disqus: ''
# mailchimp-list: 
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  zikapanam:
    name: zikapanam 
    display_name: ZAP   
    avatar: assets/images/avatar.png
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: contact@zikapanam.fr
    web: https://www.zikapanam.fr
    description: "Rédacteur de ce blog, l'équipe ZIKAPANAM."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
