# Deployment
host: 0.0.0.0
port: 8082 

# Site
name: "Asso Zikapanam"
title: "Asso Zikapanam"
description: "🎶 Zikapanam | La musique, ensemble ! 🎸 <br>
  🎤 Jams, répètes, scènes ouvertes & concerts <br>
  🎵 Du jazz au métal, de la musique trad à celle de chambre <br>
  📍 Paris & petite couronne <br>
  🤝 Rejoins-nous <br>"
logo_baseline: assets/images/logo-zikapanam-baseline-bleu-fonce.png
logo_no_baseline: assets/images/logo-zikapanam-no-baseline-bleu-fonce.png
favicon: assets/images/favicon.ico'
baseurl: 
# google_analytics: 'UA-46278016-1'
search:
disqus: 
mailchimp-list: 'https://zikapanam.us17.list-manage.com/subscribe/post?u=e285f1402aa04caeb98623bf5&id=b4caddf1c4&f_id=00414de0f0'
include: ["_pages", "_newsletter", ".well-known"]
permalink: /:title/

collections:
  coll_testimonials:
  testimonials_pjc:
  testimonials_pjc_orga:
  testimonials_mip:
  testimonials_mip_orga:

# Authors
authors:
  zikapanam:
    name: zikapanam 
    display_name: ZAP   
    avatar: assets/images/logo-zikapanam-no-baseline-bleu-fonce.png
    email: contact@zikapanam.fr
    web: https://www.blog.zikapanam.fr
    description: "Rédacteur de ce blog, l'équipe ZIKAPANAM."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
  
# Archives
jekyll-archives:
  enabled:
    - categories
  enabled:
    - month  
  layouts:
    category: categories
    month: monthly
  permalinks:
    category: '/category/:name/'
    month: '/:year-:month/'    

# Pagination 
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
